aws:
  cli_profile: "ec2-training"
  iam_role_arn: "arn:aws:iam::084375547262:role/EC2-Training-Role"
  iam_instance_profile: "EC2-Training-Role"
  region: "eu-central-1"
  s3_bucket: "grateful-dead-chatbot"
  session_name: "EC2-Training-Session"

ec2:
  ami_id: "ami-0745b7d4092315796"  # Deep Learning AMI Example
  instance_type: "t3.large"
  key_pair_name: "EC2-Training-Key"
  volume_size: 100  # EBS volume size
  use_spot_instance: true  # fasle for On-Demand instances

training:
  dataset_path: "data/"
  model: "gpt2"
  fine_tune: true
  num_layers_to_unfreeze: 20
  epochs: 50 
  checkpoint_interval: 5
  checkpoint_dir: "checkpoints/"
  checkpoint_file: "model_checkpoint.pth" 
  resume_from_checkpoint: true
