aws:
  iam_role_arn: "arn:aws:iam::084375547262:role/EC2-Training-Role" # Do we need this anymore?
  iam_instance_profile: "EC2-Training-Role"
  region: "eu-central-1"
  s3_bucket: "grateful-dead-chatbot"
  key_pair_name: "EC2-Training-Key"

ec2:
  ami_id: "ami-0745b7d4092315796"  # Deep Learning AMI Example
  instance_type: "t3.large"
  volume_size: 100  # EBS volume size
  use_spot_instance: true  # Or On-Demand instances

training:
  model: "gpt2" 
  epochs: 50 
  checkpoint_interval: 5
  resume_from_checkpoint: true
