aws:
  cli_profile: "ec2-training"
  iam_role_arn: "arn:aws:iam::084375547262:role/EC2-Training-Role"
  iam_instance_profile: "EC2-Training-Role"
  region: "eu-central-1"
  project_name: "grateful-dead-chatbot"
  s3_bucket_checkpoints: "grateful-dead-chatbot/checkpoints"
  s3_bucket_logs: "grateful-dead-chatbot/logs"
  s3_bucket_data: "grateful-dead-chatbot/class_test"
  session_name: "EC2-Training-Session"

ec2:
  ami_id: "ami-0745b7d4092315796"  # Deep Learning AMI Example
  instance_type: "t3.large"
  key_pair_name: "EC2-Training-Key"
  volume_size: 100  # EBS volume size
  use_spot_instance: true  # fasle for On-Demand instances

training:
  dataset_path: "data/"
  model: "resnet50" # "resnet50", "resnet101", "inceptionv3", "gpt2", "dcgan"
  fine_tune: true
  epochs: 2 
  checkpoint_interval: 1
  checkpoint_dir: "checkpoints/"
  checkpoint_prefix: "checkpoint" 
  resume_from_checkpoint: true
