[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310']
exclude = '''
/(
    \.git
  | \.venv
  | build
  | dist
  | __pycache__
  | .*_test\.py
)/
'''

[tool.ruff]
line-length = 88
target-version = "py38"
select = ["E", "F", "W", "I"]  # Linting rules (Errors, Flake8, Warnings, Imports)
ignore = ["E203", "E501"]  # Ignore line spacing & long lines
fixable = ["I"]  # Allow Ruff to auto-fix import sorting

[tool.mypy]
python_version = 3.8
ignore_missing_imports = true
disallow_untyped_defs = false
disallow_untyped_calls = false
strict_optional = true
warn_unused_ignores = true
warn_return_any = true
warn_unused_configs = true
show_error_codes = true
